<a href="https://colab.research.google.com/github/peterpanw/Machine_learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #对iris数据集进行训练分类
from sklearn import  datasets
from sklearn.model_selection import  train_test_split
from sklearn.metrics import  classification_report,confusion_matrix #对模型分类结果进行评估的两个模型
import operator  #https://blog.csdn.net/u010339879/article/details/98304292，关于operator的使用
import random

In [ ]:
def knn(x_test, x_data, y_data, k):
  x_data_size = x_data.shape[0]  # 计算样本数量
  diffMat = np.tile(x_test,(x_data_size,1)) - x_data# 复制x_test，计算x_test与每一个样本的差值
  sqDiffMat = diffMat**2# # 计算差值的平方
  sqDistance = sqDiffMat.sum(axis= 1) # 求和
  distances = sqDistance**0.5 # 开方
  sortedDistance = distances.argsort()# 从小到大排序
  classCount = {}
  for i in range(k):
    vlabel = y_data[sortedDistance[i]] # 获取标签
    classCount[vlabel] = classCount.get(vlabel,0)+1# 统计标签数量
  sortedClassCount = sorted(classCount.items(),key = operator.itemgetter(1), reverse = True) # 根据operator.itemgetter(1)-第1个值对classCount排序，然后再取倒序
  return sortedClassCount[0][0]

In [ ]:
 iris = datasets.load_iris()# 载入数据
 x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [ ]:
prodictions = []
for i in range(x_test.shape[0]):
   prodictions.append(knn(x_test[i],x_train,y_train,5))
print(prodictions)

[0, 2, 1, 0, 2, 1, 1, 2, 2, 0, 1, 2, 0, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 2, 0, 1, 2, 1, 2, 2, 0, 2, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 2, 1, 1]


In [ ]:
print(classification_report(y_test, prodictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.88      0.94      0.91        16
           2       0.93      0.88      0.90        16

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45



In [ ]:
print(confusion_matrix(y_test,prodictions))

[[13  0  0]
 [ 0 15  1]
 [ 0  2 14]]


这个混淆矩阵意味着，有全部13个实际为类0的被预测为类0；16个实际为类1当中15个被正确预测为类1，1个被预测为类2；16个实际为类2当中14个被正确预测为类2,2个被预测为类1。